overwrite: true
schema:
  - https://${SWELL_STORE_ID}.swell.store/graphql:
      headers:
        Authorization: ${SWELL_STOREFRONT_PUBLIC_KEY}
documents: 'lib/**/*.graphql'
generates:
  lib/swell/__generated__/graphql.ts:
    plugins: ['typescript', 'typescript-operations', 'typescript-graphql-request']
    config:
      preResolveTypes: false
      maybeValue: T
      inputMaybeValue: T | undefined
      rawRequest: true
      avoidOptionals:
        field: true
        inputValue: true
        object: true
        defaultValue: true
